server:
  port: 8080
  servlet:
    context-path: /bootcamp


spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: postgres://exkjmmyzkmtvnd:e2361652b4047a1ce13da455f140e0a2e27f76600f1a8708ae696df7e5d41166@ec2-54-166-167-192.compute-1.amazonaws.com:5432/d6rs6ml9pnimp1
    username: exkjmmyzkmtvnd
    password: e2361652b4047a1ce13da455f140e0a2e27f76600f1a8708ae696df7e5d41166
  jpa:
    show-sql: true
    database-plataform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none
application:
  description: "Projeto criado na semana dev week DIO e Santander"
